site_name: Using SPDX
site_description: Information on how to use the System Package Data Exchange (SPDX) specification
site_author: The Linux Foundation and its Contributors
site_url: https://spdx.github.io/using/
repo_url: https://github.com/spdx/using/
edit_uri: "edit/main/docs"  # set to an empty string to disable edit links
copyright: Using SPDX Copyright © 2024-2025, The Linux Foundation and its Contributors.
use_directory_urls: true
theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo-white.svg
  features:
    - content.action.edit
    - navigation.instant
    - navigation.instant.progress
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
plugins:
- git-revision-date-localized # Use mkdocs-git-revision-date-localized-plugin
- search
- social
- tags
markdown_extensions:
- admonition
- abbr
- def_list
- pymdownx.details
- pymdownx.superfences
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
strict: true
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
nav:
- Home: index.md
- Getting started: getting-started.md
- Cross referencing: cross-reference.md
- Including security information in a SPDX document: security-info-in-spdx.md
- How to implement VEX in SPDX: how-to-vex.md
- Using SPDX License List short identifiers in source files: license-id-in-source.md
- Using SPDX to comply with norms, standards and regulation: comply-with-norms.md
- Differences from previous editions: diffs-from-previous-editions.md
- Browse by tags: tags.md
