site_name: Using SPDX
site_description: Information on how to use the System Package Data Exchange (SPDX) specification
site_author: The Linux Foundation and its Contributors
site_url: https://spdx.github.io/using/
repo_url: https://github.com/spdx/using/
edit_uri: "edit/main/docs"  # set to an empty string to disable edit links
copyright: Using SPDX Copyright © 2024-2025, The Linux Foundation and its Contributors.
use_directory_urls: true
theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo-white.svg
  features:
    - content.action.edit
    - navigation.instant
    - navigation.instant.progress
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
plugins:
- git-revision-date-localized # Use mkdocs-git-revision-date-localized-plugin
- search
- social
- tags
markdown_extensions:
- admonition
- abbr
- def_list
- pymdownx.details
- pymdownx.superfences
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
strict: true
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
nav:
- Home: index.md
- getting-started.md
- cross-reference.md
- security-info-in-spdx.md
- license-id-in-source.md
- comply-with-norms.md
- Differences between versions:
  - v1.0 - v2.0: diff/v1.2-v2.0.md
  - v2.0 - v2.1: diff/v2.0-v2.1.md
  - v2.1 - v2.2: diff/v2.1-v2.2.md
  - v2.2 - v2.2.1: diff/v2.2-v2.2.1.md
  - v2.2.1 - v2.2.2: diff/v2.2.1-v2.2.2.md
  - v2.2.2 - v2.3: diff/v2.2.2-v2.3.md
  - v2.3 - v3.0: diff/v2.3-v3.0.md
  - v3.0 - v3.0.1: diff/v3.0-v3.0.1.md
- Browse by tags: tags.md
