# SPDX-License-Identifier: MIT
on:
  pull_request:
    paths:
      - 'docs/*.md'  # For code snippets inside a document
      - 'examples/jsonld/*.json'
  push:
    paths:
      - 'docs/*.md'
      - 'examples/jsonld/*.json'
  workflow_dispatch: {}
jobs:
  validate-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  #v4.2.0
      - name: Install Python dependencies
        run: |
          python3 -m pip install check-jsonschema==0.29.3 pyshacl==0.26.0 spdx3-validate==0.0.4
      - name: Install dependencies
        run: |
          sudo apt install -y gawk  
      - name: Check examples
        run: |
          ./bin/check-examples.sh
